name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Show build environment
        run: |
          echo "Rust version: $(rustc --version)"
          echo "Cargo version: $(cargo --version)"
          echo "PostgreSQL version: $(psql --version)"
      - name: Init DB
        run: cargo install --version='~0.7' sqlx-cli --no-default-features --features rustls,postgres && ./scripts/init_db.sh
      - name: Lint
        run: cargo clippy --verbose -- -D warnings
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
